services:
  gemini-api:
    # build: .
    image: ghcr.io/repsu/gemini-business2api:ci-main
    pull_policy: always
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
